Support both https and http
Talend/org.ops4j.pax.url pull request #3
Opened 2018-03-20 06:24 UTC by ggu-talend

Currently, if set both https and http in java properties, use https only.
When url is http, won't work for https proxy. 
So this fixing will add both for MavenResolver (AetherBasedResolver).

2018-03-20 06:30 UTC, ggu-talend commented
Because 
- if url is https, work with https or http proxies. sure, if provide https proxy, will use it directly.
- if url is http, only work for http proxy.

2018-03-20 09:51 UTC, sgandon requested changes
is it possible to add some unit tests ?

2018-03-28 11:53 UTC, sgandon commented
Great tests GGU, thanks !
Could you also change the version too in *pax-url-aether/pom.xml* something like : 2.4.6-Talend if it is a fix.

2018-03-29 09:06 UTC, sgandon approved these changes

2018-03-29 09:09 UTC, merged